export { Home } from "./screens/home/index";
export { Login } from "./screens/login/index";
export { Battle } from "./screens/battle/index";
export { Hero } from "./hero/index";
export  { DrawMonster } from "./drawMonster/index";
export  { TaskNumbers } from "./tasks/taskNumbers/index";
export  { BattleWinWindow } from "./screens/battleWinWindow/index";
export  { DrawSpell } from "./drawSpell/index";
export  { TableResults } from "./screens/tableResults/index";
export  { TaskRandomMathOperation } from "./tasks/taskRandomMathOperation/index";
export { TaskWordsAudio }  from "./tasks/taskWordsAudio/index";
export { TaskTrueOrFalse }  from "./tasks/taskTrueOrFalse/index";
export  { TaskWordTranslate} from "./tasks/taskWordTranslate/index";
export  {TaskLetterShuffle } from "./tasks/taskLetterShuffle/index";
export {TaskAnimalTasks} from "./tasks/taskAnimalTasks/index";
export {TaskExtraWords} from "./tasks/taskExtraWords/index";
export {TaskNextNumber} from "./tasks/taskNextNumber/index";
export {TaskAntonym} from "./tasks/taskAntonym/index";
export {TaskInputLetter} from "./tasks/taskInputLetter/index";
export {TaskCapitals} from "./tasks/taskCapitals/index";
export {TaskFinishTheSentence} from "./tasks/taskFinishTheSentence/index";
export  {TaskAuthorOfBook} from "./tasks/taskAuthorOfBook/index";
export {TaskItsBaby} from "./tasks/taskItsBaby/index";
export {LoadingScreen} from "./loadingScreen/index";